name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: curamet-onboarding
  REGION: europe-west1
  SERVICE_NAME: demo-service
  PREFIX: nr
  VERSION: 0.0.3
  REPOSITORY: curamet-repo
  IMAGE_URL: europe-docker.pkg.dev/curamet-onboarding/curamet-repo/am-demo-service:0.0.3

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          cd terraform
          chmod +x push-docker-image.sh
          ./push-docker-image.sh

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $PREFIX-$SERVICE_NAME \
            --image $IMAGE_URL \
            --region $REGION \
            --platform managed
